apiVersion: v1
kind: Pod
metadata:
  name: openjdk8-pod
  labels:
    app: openjdk7
spec:
  containers:
  - name: openjdk7
    image: openjdk:7-jdk
    command: ["java", "-version"]

---
apiVersion: v1
kind: Pod
metadata:
  name: openjdk21-pod
  labels:
    app: openjdk21
spec:
  containers:
  - name: openjdk21
    image: openjdk:21-jdk
    command: ["java", "-version"]
