apiVersion: v1
kind: Deployment
metadata:
  name: runtime
  labels:
    app: runtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runtime
  template:
    metadata:
      labels:
        app: runtime
    spec:
      containers:
      - name: openjdk7
        image: openjdk:7-jdk
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 30; done"]
      - name: openjdk21
        image: openjdk:21-jdk
        command: ["/bin/sh"]
        args: ["-c", "while true; do sleep 30; done"]


