apiVersion: v1
kind: Pod
metadata:
  name: openjdk8-pod
  labels:
    app: openjdk7
spec:
  containers:
  - name: openjdk7
    image: openjdk:7-jdk
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 30; done"]

---
apiVersion: v1
kind: Pod
metadata:
  name: openjdk21-pod
  labels:
    app: openjdk21
spec:
  containers:
  - name: openjdk21
    image: openjdk:21-jdk
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 30; done"]
