apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-f
  labels:
    app: kafka-g
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka-a
  template:
    metadata:
      labels:
        app: kafka-a
    spec:
      containers:
      - name: kafka1
        image: bitnami/kafka:latest
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-c:2181"
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-b:9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-b
spec:
  ports:
  - port: 9092
    targetPort: 9092
  selector:
    app: kafka-a
