apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: traffic-split
spec:
  hosts:
  - "*"
  http:
  - route:
    - destination:
        host: my-service
        port:
          number: 80
      weight: 50
    - destination:
        host: my-service
        port:
          number: 81
      weight: 50